spring:
  application:
    name: ecommerce
  data:
    redis:
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
  sql:
    init:
      mode: always

springdoc:
  packages-to-scan: org.wisdom.ecommerce
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  use-fqn: true
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha