name: Auto Re-run PR Workflows on Master Push (Read-only)

on:
  push:
    branches:
      - master

jobs:
  trigger-pr-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find open PRs
        id: find-prs
        run: |
          prs=$(gh pr list --state open --json number --jq '.[].number')
          echo "prs=$(echo $prs | base64)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger workflow for PRs
        run: |
          prs=$(echo "${{ env.prs }}" | base64 --decode)
          for pr in $prs; do
            echo "✅ No conflicts detected. Triggering workflow for PR #$pr..."
            gh workflow run pr-check.yml --repo ${{ github.repository }} --ref refs/pull/$pr/head || echo "⚠️ Failed to trigger workflow for PR #$pr"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}