name: Auto Re-run PR Workflows on Master Push

on:
  push:
    branches:
      - master

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find open PRs
        id: find-prs
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | select(.headRefName != "master") | {number: .number, branch: .headRefName}')
          echo "prs=$(echo $prs | base64)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check merge conflicts and trigger workflow
        run: |
          prs=$(echo "${{ env.prs }}" | base64 --decode)
          for row in $(echo "$prs" | jq -c '.'); do
            pr_number=$(echo $row | jq -r '.number')
            pr_branch=$(echo $row | jq -r '.branch')

            echo "🔍 Checking merge status for PR #$pr_number ($pr_branch)..."

            merge_status=$(gh pr view $pr_number --json mergeable --jq '.mergeable')

            if [[ "$merge_status" == "CONFLICTING" ]]; then
              echo "❌ Merge conflict detected in PR #$pr_number ($pr_branch). Skipping workflow trigger."
            else
              echo "✅ No conflicts detected. Triggering workflow for PR #$pr_number..."
              gh workflow run pr-check.yml --repo ${{ github.repository }} --ref refs/pull/$pr_number/head
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}